---

- name: Install Google Chrome
  homebrew_cask: name=google-chrome state=present
  notify: brew cask cleanup

- name: Toggle swipe navigation
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: "{{ google_chrome_AppleEnableSwipeNavigateWithScrolls }}"
  notify:
    - killall Google Chrome
